name: Codecov

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
